import base64

ICO_DATA = base64.b64decode(
    b'AAABAAIAEBAAAAEAIAAoBQAAJgAAACAgAAABACAAKBQAAE4BAAAoAAAAEAAAACAAAAABACAAAAAAAAA'
    b'AAAEAIABCBAAAgIAAAEBAACAgAAAQEAABgYAAAQEAAAGBgAABgYAAAYGAAAGBgAAGBgAAGBgAAGBgA'
    b'AGBgAAGBgAAGBgAAQECAAEBAgABAQIAAQECAAEBAgABAQIAAQECAAEBAgABAQIAAQECAAEBAgABAQI'
    b'AAQECAAEBAgABAQIAAQECAAEBAgABAQIAAQECAAEBAgAEBAYACAQGAAgEBgAIBAYACAQGAAgEBgAIB'
    b'AYACAQGAAgEBgAIBAYACAQGAAgEBgAIBAYACAQGAAgEBgAIBAYACAQGAAwMCAAADAwIAAAMDggADAg'
    b'IAAwICAAADAgIAAwICAAADAgIAAwICAAADAgIAAwICAAADAgIAAwICAAADAgIAAwICAAADAgIAAwMC'
    b'AAADAwIAAwMEAAIDBAACAwQAAgMEAAIDBAACAwQAAgMEAAIDBAACAwQAAgMEAAIDBAACAwQAAgMEAA'
    b'IDBAACAwQAAgMEAAIDBAACAwQAAgMEAAKAgAACgIAAAoCAAACgIAAAoCAAACgIAAAoCAAACgIAAAoC'
    b'AAAICAAACAgAAAgIAAAICAAACAgAAAgIAAAICAAACAgAAAgIAAaGgAAGhoAABoaAAAYGAAAGBgAABg'
    b'YAAAGBgAABgYAAAGBgAAGBgAABgYAAAGBgAABgYAAAGBgAABgYAAAGBgAABoaAAaGgAAGhoAABoaAA'
    b'aGgAAGhoAABoaAAaGgAAGhoAABoaAAaGgAAGhoAABoaAAaGgAAGhoAABoaAAaGgACAgIAAgICAAIC'
    b'AgACAgIAAgICAAICAgACAgIAAgICAAICAgACAgIAAgICAAICAgACAgIAAgICAAICAgACAgIAAgICAA'
    b'MDAgADBAIAAwQCAAMEAgADBAIAAwQCAAMEAgADBAIAAwQCAAMEAgADBAIAAwQCAAMEAgADBAIAAwQC'
    b'AAMEAgADBAIAAwQDAAMFAwADBgMAAwYDAAMFAwADBgMAAwYDAAMGAwADBgMAAwYDAAMGAwADBgMAAw'
    b'YDAAMGAwADBgMAAwYDAAMFAwADBQMAAwYDAAMGAwADBgMAAwYDAAMGAwADBgMAAwYDAAMGAwADBgMA'
    b'AwYDAAMGAwADBgMAAwYDAAMGAwADBgMAAwYDAAMEAwADBQMAAwYDAAMGAwADBgMAAwYDAAMGAwADBg'
    b'MAAwYDAAMGAwADBgMAAwYDAAMGAwADBgMAAwYDAAMGAwADBgMAAwQDAAMEAwADBQMAAwYDAAMGAwAD'
    b'BgMAAwYDAAMGAwADBgMAAwYDAAMGAwADBgMAAwYDAAMGAwADBgMAAwYDAAMGAwADBgMAAwQDAAICA'
    b'gACAgIAAgICAAICAgACAgIAAgICAAICAgACAgIAAgICAAICAgACAgIAAgICAAICAgACAgIAAgICAA'
    b'ICAgACAgIAaGgAAGhoAABoaAAaGgAAGhoAABoaAAaGgAAGhoAABoaAAaGgAAGhoAABoaAAaGgAAGh'
    b'oAABoaAAaGgAAGhoAABoaAAaGgAAGhoAABoaAAaGgAAGhoAABoaAAaGgAAGhoAABoaAAaGgAAGhoA'
    b'ABoaAAaGgAAGhoAABoaAAaGgAAICAgACAgIAAgICAAICAgACAgIAAgICAAICAgACAgIAAgICAAICA'
    b'gACAgIAAgICAAICAgACAgIAAgICAAICAgACAgIAAgICAAICAgACAgIAAgICAAICAgACAgIAAgICAA'
    b'ICAgACAgIAAgICAAICAgACAgIAAgICAAICAgACAgIAAgICAAAgICAAICAgACAgIAAgICAAICAgACA'
    b'gIAAgICAAICAgACAgIAAgICAAICAgACAgIAAgICAAICAgACAgIAAgICAAICAgACAgIAAgICAAICAg'
    b'ACAgIAAgICAAICAgACAgIAAgICAAICAgACAgIAAgICAAICAgACAgIAAgICAAICAgACAgIAAgICAAI'
    b'CAgACAgIAAgICAAICAgACAgIAAgICAAICAgACAgIAAgICAAICAgACAgIAAgICAAICAgACAgIAAgIC'
    b'AAICAgACAgIAAgICAAICAgACAgIAAgICAAICAgACAgIAAgICAAICAgACAgIAAgICAAICAgACAgIAA'
    b'gICAAICAgACAgIAAgICAAICAgACAgIAAgICAAICAgACAgIAAgICAAICAgACAgIAAgICAAICAgACAg'
    b'IAAgICAAICAgACAgIAAgICAAICAgACAgIAAgICAAICAgACAgIAAgICAAICAgACAgIAAgICAAICAgA'
    b'CAgIAAgICAAICAgACAgIAAgICAAICAgACAgIAAgICAAICAgACAgIAICAgAA==')

try:
    with open("enigma.ico", "wb") as icon_file:
        icon_file.write(ICO_DATA)
    print("Successfully created enigma.ico")
except Exception as e:
    print(f"An error occurred: {e}")

